version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - "buzzer"
    labels:
      com.datadoghq.ad.logs: '[{"source": "buzzer", "service": "nginx"}]'
      com.datadoghq.ad.check_names: '["nginx"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"nginx_status_url": "http://%%host%%:8080/nginx_status"}]'
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    labels:
      com.datadoghq.ad.logs: '[{"source": "buzzer", "service": "certbot"}]'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  buzzer:
    image: ashwinjv/buzzer:v1.1.0
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - DATADOG_HOST=datadog
    labels:
      com.datadoghq.ad.logs: '[{"source": "buzzer", "service": "buzzer"}]'
  datadog:
    image: datadog/agent:latest
    links:
      - nginx
      - certbot
      - buzzer
    environment:
      - DD_API_KEY=__API_KEY__
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_AC_EXCLUDE="name:ec2-user_datadog_1"
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
